# Agenda
* Numpy
* Pandas
* Lab


# Introduction


## Create a new notebook for your code-along:

From our submission directory, type:
    
    jupyter notebook

From the IPython Dashboard, open a new notebook.
Change the title to: "Numpy and Pandas"

# Introduction to Numpy

* Overview
* ndarray
* Indexing and Slicing

More info: [http://wiki.scipy.org/Tentative_NumPy_Tutorial](http://wiki.scipy.org/Tentative_NumPy_Tutorial)


## Numpy Overview

* Why Python for Data? Numpy brings *decades* of C math into Python!
* Numpy provides a wrapper for extensive C/C++/Fortran codebases, used for data analysis functionality
* NDAarray allows easy vectorized math and broadcasting (i.e. functions for vector elements of different shapes)

In [2]:
import numpy as np

### Creating ndarrays

An array object represents a multidimensional, homogeneous array of fixed-size items. 

In [56]:
# Creating arrays
a = np.zeros((3))
b = np.ones((2,3))
c = np.random.randint(1,10,(2,3,4))
d = np.arange(0,11,1)
#?np.ones((2,3))# displays function descriptions
?np.arange(0,11,1)

What are these functions?

    arange?

In [55]:
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
# Note the way each array is printed:
a,b,c,d

(array([ 0.,  0.,  0.]), array([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]), array([[[7, 6, 2, 8],
         [9, 1, 8, 3],
         [7, 4, 1, 6]],
 
        [[4, 1, 7, 2],
         [8, 3, 1, 2],
         [7, 5, 6, 9]]]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [ ]:
## Arithmetic in arrays is element wise

In [57]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [58]:
c = a-b
c

array([20, 29, 38, 47])

In [59]:
b**2

array([0, 1, 4, 9])

## Indexing, Slicing and Iterating

In [7]:
# one-dimensional arrays work like lists:
a = np.arange(10)**2

In [8]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [9]:
a[2:5]

array([ 4,  9, 16])

In [ ]:
# Multidimensional arrays use tuples with commas for indexing
# with (row,column) conventions beginning, as always in Python, from 0

In [10]:
b = np.random.randint(1,100,(4,4))

In [11]:
b

array([[74,  2,  7, 68],
       [68, 40, 20, 28],
       [22, 13, 56, 20],
       [93, 37, 87, 90]])

In [12]:
# Guess the output
print(b[2,3])
print(b[0,0])


20
74


In [13]:
b[0:3,1],b[:,1]

(array([ 2, 40, 13]), array([ 2, 40, 13, 37]))

In [14]:
b[1:3,:]

array([[68, 40, 20, 28],
       [22, 13, 56, 20]])

# Introduction to Pandas

* Object Creation
* Viewing data
* Selection
* Missing data
* Grouping
* Reshaping
* Time series
* Plotting
* i/o
 

_pandas.pydata.org_

## Pandas Overview

_Source: [pandas.pydata.org](http://pandas.pydata.org/pandas-docs/stable/10min.html)_

In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [16]:
dates = pd.date_range('20140101',periods=6)
dates

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [119]:
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
z = pd.DataFrame(index = df.index, columns = df.columns)
df.columns

Index([u'A', u'B', u'C', u'D'], dtype='object')

In [122]:
# Index, columns, underlying numpy data
#df.T #transpose
df

A         B         C         D
2014-01-01 -1.017602  0.967446  1.059878  0.965787
2014-01-02 -0.266418 -0.029082 -1.083031  0.244235
2014-01-03 -0.950667  1.387373 -1.795730 -1.947188
2014-01-04 -0.312885  0.688146 -0.172165  2.129628
2014-01-05 -0.186990  0.150889 -1.921189  1.333134
2014-01-06 -0.975132  0.893387 -0.860510 -0.245226

In [19]:
df2 = pd.DataFrame({ 'A' : 1.,
                         'B' : pd.Timestamp('20130102'),
                         'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                         'D' : np.array([3] * 4,dtype='int32'),
                         'E' : 'foo' })
    

df2

A          B    C  D    E
0  1.0 2013-01-02  1.0  3  foo
1  1.0 2013-01-02  1.0  3  foo
2  1.0 2013-01-02  1.0  3  foo
3  1.0 2013-01-02  1.0  3  foo

In [20]:
# With specific dtypes
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E            object
dtype: object

#### Viewing Data

In [21]:
df.head() #1st 5 values

A         B         C         D
2014-01-01 -1.451074 -0.440934  1.768428 -0.962487
2014-01-02  0.571062  0.072596 -0.418122 -1.076960
2014-01-03 -0.259461 -0.862312 -0.067189 -0.501441
2014-01-04 -1.563310 -0.512924 -0.636389 -0.181439
2014-01-05  1.395762  1.788944  0.244133  0.406147

In [22]:
df.tail() #last 5 values

A         B         C         D
2014-01-02  0.571062  0.072596 -0.418122 -1.076960
2014-01-03 -0.259461 -0.862312 -0.067189 -0.501441
2014-01-04 -1.563310 -0.512924 -0.636389 -0.181439
2014-01-05  1.395762  1.788944  0.244133  0.406147
2014-01-06  0.028327 -0.253409 -0.049241 -1.187058

In [23]:
df.index

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [24]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.213116 -0.034673  0.140270 -0.583873
std    1.150602  0.944848  0.855060  0.616312
min   -1.563310 -0.862312 -0.636389 -1.187058
25%   -1.153170 -0.494927 -0.330389 -1.048342
50%   -0.115567 -0.347172 -0.058215 -0.731964
75%    0.435378 -0.008905  0.170790 -0.261439
max    1.395762  1.788944  1.768428  0.406147

In [98]:
?df.sort_values(by='B')

In [102]:
dff=df.sort_values(by='C', ascending=False)
dff

A      B         C         D
7  foo  three  2.128290  0.946130
0  foo    one  0.576822  1.398421
1  bar    one  0.495445  0.289405
3  bar  three  0.477903  1.846258
5  bar    two -0.497851 -0.847734
6  foo    one -0.688802  0.149671
4  foo    two -0.874102  0.066062
2  foo    two -1.124176 -0.175350

### Selection

In [32]:
df[['A','B']] # The second bracket makes sure the data type stays at dataframe and not a series

A         B
2014-01-03 -0.259461 -0.862312
2014-01-04 -1.563310 -0.512924
2014-01-01 -1.451074 -0.440934
2014-01-06  0.028327 -0.253409
2014-01-02  0.571062  0.072596
2014-01-05  1.395762  1.788944

In [60]:
df[0:3]

A         B         C         D
2014-01-03 -0.259461 -0.862312 -0.067189 -0.501441
2014-01-04 -1.563310 -0.512924 -0.636389 -0.181439
2014-01-01 -1.451074 -0.440934  1.768428 -0.962487

In [38]:
# By label
df.loc[dates[0]]
#df[0:]

A   -1.451074
B   -0.440934
C    1.768428
D   -0.962487
Name: 2014-01-01 00:00:00, dtype: float64

In [61]:
# multi-axis by label
df.loc[:,['A','B']]

A         B
2014-01-03 -0.259461 -0.862312
2014-01-04 -1.563310 -0.512924
2014-01-01 -1.451074 -0.440934
2014-01-06  0.028327 -0.253409
2014-01-02  0.571062  0.072596
2014-01-05  1.395762  1.788944

In [62]:
# Date Range
df.loc['20140102':'20140104',['B']]

B
2014-01-03 -0.862312
2014-01-04 -0.512924
2014-01-02  0.072596

In [63]:
# Fast access to scalar
df.at[dates[1],'B']

0.072596212365732105

In [64]:
# iloc provides integer locations similar to np style
df.iloc[3:]

A         B         C         D
2014-01-06  0.028327 -0.253409 -0.049241 -1.187058
2014-01-02  0.571062  0.072596 -0.418122 -1.076960
2014-01-05  1.395762  1.788944  0.244133  0.406147

### Boolean Indexing

In [105]:
df[(df.C > 0) & (df.A=='foo')] # Basically a 'where' operation # where conditions inside the bracket is true

A      B         C         D
0  foo    one  0.576822  1.398421
7  foo  three  2.128290  0.946130

### Setting

In [106]:
df_posA = df.copy() # Without "copy" it would act on the dataset

df_posA[df_posA.A < 0] = -1*df_posA

In [107]:
df_posA

A      B         C         D
0  foo    one  0.576822  1.398421
1  bar    one  0.495445  0.289405
2  foo    two -1.124176 -0.175350
3  bar  three  0.477903  1.846258
4  foo    two -0.874102  0.066062
5  bar    two -0.497851 -0.847734
6  foo    one -0.688802  0.149671
7  foo  three  2.128290  0.946130

In [68]:
#Setting new column aligns data by index
s1 = pd.Series([1,2,3,4,5,6],index=pd.date_range('20140102',periods=6))

In [69]:
s1

2014-01-02    1
2014-01-03    2
2014-01-04    3
2014-01-05    4
2014-01-06    5
2014-01-07    6
Freq: D, dtype: int64

In [70]:
df['F'] = s1

In [71]:
df

A         B         C         D    F
2014-01-03 -0.259461 -0.862312 -0.067189 -0.501441  2.0
2014-01-04 -1.563310 -0.512924 -0.636389 -0.181439  3.0
2014-01-01 -1.451074 -0.440934  1.768428 -0.962487  NaN
2014-01-06  0.028327 -0.253409 -0.049241 -1.187058  5.0
2014-01-02  0.571062  0.072596 -0.418122 -1.076960  1.0
2014-01-05  1.395762  1.788944  0.244133  0.406147  4.0

### Missing Data

In [39]:
# Add a column with missing data
df1 = df.reindex(index=dates[0:4],columns=list(df.columns) + ['E'])

In [40]:
df1.loc[dates[0]:dates[1],'E'] = 1

In [41]:
df1

A         B         C         D    E
2014-01-01 -1.451074 -0.440934  1.768428 -0.962487  1.0
2014-01-02  0.571062  0.072596 -0.418122 -1.076960  1.0
2014-01-03 -0.259461 -0.862312 -0.067189 -0.501441  NaN
2014-01-04 -1.563310 -0.512924 -0.636389 -0.181439  NaN

In [113]:
# find where values are null
pd.isnull(df1)
#pd.isnull(df1).sum() #number of missing values
#pd.isnull(df1['E']).sum() #number of missing values

A      B      C      D      E
2014-01-01  False  False  False  False  False
2014-01-02  False  False  False  False  False
2014-01-03  False  False  False  False   True
2014-01-04  False  False  False  False   True

### Operations

In [43]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.213116 -0.034673  0.140270 -0.583873
std    1.150602  0.944848  0.855060  0.616312
min   -1.563310 -0.862312 -0.636389 -1.187058
25%   -1.153170 -0.494927 -0.330389 -1.048342
50%   -0.115567 -0.347172 -0.058215 -0.731964
75%    0.435378 -0.008905  0.170790 -0.261439
max    1.395762  1.788944  1.768428  0.406147

In [44]:
df.mean(),df.mean(1) # Operation on two different axes

(A   -0.213116
 B   -0.034673
 C    0.140270
 D   -0.583873
 dtype: float64, 2014-01-03   -0.422600
 2014-01-04   -0.723516
 2014-01-01   -0.271517
 2014-01-06   -0.365345
 2014-01-02   -0.212856
 2014-01-05    0.958747
 dtype: float64)

In [117]:
df['D'].mean()

0.4591080514913589

### Applying functions

In [123]:
df

A         B         C         D
2014-01-01 -1.017602  0.967446  1.059878  0.965787
2014-01-02 -0.266418 -0.029082 -1.083031  0.244235
2014-01-03 -0.950667  1.387373 -1.795730 -1.947188
2014-01-04 -0.312885  0.688146 -0.172165  2.129628
2014-01-05 -0.186990  0.150889 -1.921189  1.333134
2014-01-06 -0.975132  0.893387 -0.860510 -0.245226

In [130]:
#df.apply(np.cumsum)#Apply cumulative sum to all columns
#df['D'].apply(np.cumsum)
#df[['D']].apply(np.cumsum) #Double [[]] keeps the data type as data frame
df.apply(np.cumsum,axis=1) #axis=1 performs operation across the rows instead of columns

A         B         C         D
2014-01-01 -1.017602 -0.050156  1.009722  1.975508
2014-01-02 -0.266418 -0.295500 -1.378531 -1.134296
2014-01-03 -0.950667  0.436706 -1.359024 -3.306212
2014-01-04 -0.312885  0.375261  0.203096  2.332724
2014-01-05 -0.186990 -0.036100 -1.957290 -0.624156
2014-01-06 -0.975132 -0.081745 -0.942254 -1.187480

In [76]:
df.apply(lambda x: x.max() - x.min()) #Subtract the minimum from the maximum for each column

A    2.959072
B    2.651256
C    2.404818
D    1.593205
F    4.000000
dtype: float64

In [79]:
def custom_func(x):
    return x.max()

df.apply(custom_func)
df.apply(lambda x: x.max()) #Same as above

A    1.395762
B    1.788944
C    1.768428
D    0.406147
F    5.000000
dtype: float64

In [80]:
# Built in string methods
s = pd.Series(['A', 'B', 'C', 'Aaba', 'Baca', np.nan, 'CABA', 'dog', 'cat'])
s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object

### Merge

In [132]:
np.random.randn(10,4)

array([[ 0.75871723, -0.3890108 ,  1.68141975, -2.32680315],
       [ 0.83239124, -1.92243917,  2.02535001, -2.45722394],
       [ 2.04773857,  0.55860604, -0.89731145, -0.48382628],
       [ 0.43642833, -1.4302038 , -0.51239898,  0.92831766],
       [ 0.91579074, -1.29993803, -0.22273416, -0.69193992],
       [ 0.45111472, -0.24547801,  1.16322553, -0.5108284 ],
       [-1.02455257,  0.18908896,  0.21834178,  0.08811347],
       [ 0.33298302,  0.87712689, -1.46598764, -0.11227882],
       [ 0.61730743, -0.28356029, -0.53164161,  1.8519048 ],
       [ 0.69990813,  1.04210036, -2.04874377,  0.6212039 ]])

In [82]:
#Concatenating pandas objects together
df = pd.DataFrame(np.random.randn(10,4))
df

0         1         2         3
0  0.388118  0.082652  0.955090  1.245819
1 -1.201722 -0.344971 -0.426717 -0.858103
2  1.963499 -1.134895 -1.887521  1.750644
3 -0.885543  0.322977  0.842660 -0.219027
4 -0.560173  1.308688  1.532623 -0.614807
5  1.183239 -0.242750  0.151408 -0.474333
6  2.019548 -0.063467 -0.185780  1.129560
7 -0.723986  1.647078  0.203859  0.877380
8 -0.186820  0.199202 -0.332006 -0.033370
9 -0.978978  0.210502  1.018843 -0.474531

In [83]:
# Break it into pieces
pieces = [df[:3], df[3:7],df[7:]]
pieces

[          0         1         2         3
 0  0.388118  0.082652  0.955090  1.245819
 1 -1.201722 -0.344971 -0.426717 -0.858103
 2  1.963499 -1.134895 -1.887521  1.750644,
           0         1         2         3
 3 -0.885543  0.322977  0.842660 -0.219027
 4 -0.560173  1.308688  1.532623 -0.614807
 5  1.183239 -0.242750  0.151408 -0.474333
 6  2.019548 -0.063467 -0.185780  1.129560,
           0         1         2         3
 7 -0.723986  1.647078  0.203859  0.877380
 8 -0.186820  0.199202 -0.332006 -0.033370
 9 -0.978978  0.210502  1.018843 -0.474531]

In [84]:
pd.concat(pieces)

0         1         2         3
0  0.388118  0.082652  0.955090  1.245819
1 -1.201722 -0.344971 -0.426717 -0.858103
2  1.963499 -1.134895 -1.887521  1.750644
3 -0.885543  0.322977  0.842660 -0.219027
4 -0.560173  1.308688  1.532623 -0.614807
5  1.183239 -0.242750  0.151408 -0.474333
6  2.019548 -0.063467 -0.185780  1.129560
7 -0.723986  1.647078  0.203859  0.877380
8 -0.186820  0.199202 -0.332006 -0.033370
9 -0.978978  0.210502  1.018843 -0.474531

In [ ]:
# Also can "Join" and "Append"
df

### Grouping


In [134]:
df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
                       'foo', 'bar', 'foo', 'foo'],
                       'B' : ['one', 'one', 'two', 'three',
                             'two', 'two', 'one', 'three'],
                       'C' : np.random.randn(8),
                       'D' : np.random.randn(8)})

In [135]:
df

A      B         C         D
0  foo    one -0.021029 -0.268464
1  bar    one  0.580510 -0.955460
2  foo    two -1.491341 -0.613809
3  bar  three -1.422685  1.625565
4  foo    two  0.194409  0.427029
5  bar    two -0.633021  0.277735
6  foo    one -4.068832  0.937604
7  foo  three  0.139248  0.485210

In [136]:
df.groupby(['A','B']).sum()# you can also apply any other funciton like mean, std, etc..

C         D
A   B                        
bar one    0.580510 -0.955460
    three -1.422685  1.625565
    two   -0.633021  0.277735
foo one   -4.089860  0.669140
    three  0.139248  0.485210
    two   -1.296932 -0.186780

In [139]:
df.groupby(['A','B']).count()# you can also apply any other funciton like mean, std, etc..

C  D
A   B          
bar one    1  1
    three  1  1
    two    1  1
foo one    2  2
    three  1  1
    two    2  2

### Reshaping

In [ ]:
# You can also stack or unstack levels

In [90]:
a = df.groupby(['A','B']).sum()
a

C         D
A   B                        
bar one    0.495445  0.289405
    three  0.477903  1.846258
    two   -0.497851 -0.847734
foo one   -0.111981  1.548092
    three  2.128290  0.946130
    two   -1.998277 -0.109288

In [91]:
# Pivot Tables
pd.pivot_table(df,values=['C','D'],index=['A'],columns=['B'])

C                             D                    
B         one     three       two       one     three       two
A                                                              
bar  0.495445  0.477903 -0.497851  0.289405  1.846258 -0.847734
foo -0.055990  2.128290 -0.999139  0.774046  0.946130 -0.054644

### Time Series


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# 100 Seconds starting on January 1st
rng = pd.date_range('1/1/2014', periods=100, freq='S')

In [ ]:
# Give each second a random value
ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)

In [ ]:
ts

In [ ]:
# Built in resampling
ts.resample('1Min').mean() # Resample secondly to 1Minutely

In [ ]:
# Many additional time series features
ts. #use tab

### Plotting


In [ ]:
ts.plot()

In [ ]:
def randwalk(startdate,points):
    ts = pd.Series(np.random.randn(points), index=pd.date_range(startdate, periods=points))
    ts=ts.cumsum()
    ts.plot()
    return(ts)

In [ ]:
# Using pandas to make a simple random walker by repeatedly running:
a=randwalk('1/1/2012',1000)

In [ ]:
# Pandas plot function will print with labels as default

In [ ]:
df = pd.DataFrame(np.random.randn(100, 4), index=ts.index,columns=['A', 'B', 'C', 'D'])
df = df.cumsum()
plt.figure();df.plot();plt.legend(loc='best') #

### I/O
I/O is straightforward with, for example, pd.read_csv or df.to_csv

#### The benefits of open source:

Let's look under x's in plt modules

# Next Steps

**Recommended Resources**

Name | Description
--- | ---
[Official Pandas Tutorials](http://pandas.pydata.org/pandas-docs/stable/10min.html) | Wes & Company's selection of tutorials and lectures
[Julia Evans Pandas Cookbook](https://github.com/jvns/pandas-cookbook) | Great resource with examples from weather, bikes and 311 calls
[Learn Pandas Tutorials](https://bitbucket.org/hrojas/learn-pandas) | A great series of Pandas tutorials from Dave Rojas
[Research Computing Python Data PYNBs](https://github.com/ResearchComputing/Meetup-Fall-2013/tree/master/python) | A super awesome set of python notebooks from a meetup-based course exclusively devoted to pandas